[workspace]
authors = ["Rifo Genadi <rifo.genadi@mbzuai.ac.ae>"]
channels = ["conda-forge"]
name = "sycophancy"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[system-requirements]
cuda = "12.8"

[dependencies]
python = "3.11.*"
pytorch-gpu = "*"
cuda-version = "12.8.*"
pip = "*"
fsspec = "<=2025.10.0"
scikit-learn = ">=1.8.0,<2"
jsonlines = ">=4.0.0,<5"

[pypi-dependencies]
pyvene = "*"
datasets = ">=4.4.0"

